import { useState } from 'react';
import { Shell, Stat, useLocal } from './shared';
import { distance, routeLength, optimize } from './domain';
type Stop = {
    id: string;
    name: string;
    lat: number;
    lng: number;
};
const depot = { id: 'depot', name: 'Base Guarulhos', lat: -23.4543, lng: -46.5337 };
export default function App() { const [stops, setStops, error] = useLocal<Stop[]>('routecraft-v1', [{ id: '1', name: 'São Paulo', lat: -23.5505, lng: -46.6333 }, { id: '2', name: 'Santo André', lat: -23.6737, lng: -46.5432 }, { id: '3', name: 'Osasco', lat: -23.5329, lng: -46.7917 }]); const [optimized, setOptimized] = useState(false); const [cost, setCost] = useState(2.5); const ordered = optimized ? optimize(depot, stops) : stops; const km = routeLength(depot, ordered); function add(e: React.FormEvent<HTMLFormElement>) { e.preventDefault(); const f = new FormData(e.currentTarget); const name = String(f.get('name')).trim(), lat = Number(f.get('lat')), lng = Number(f.get('lng')); if (!name || !Number.isFinite(lat) || !Number.isFinite(lng) || Math.abs(lat) > 90 || Math.abs(lng) > 180)
    return; setStops([...stops, { id: crypto.randomUUID(), name, lat, lng }]); e.currentTarget.reset(); } return <Shell name="Routecraft" title="Planeje o caminho da entrega." description="Compare sequências de paradas e explore a lógica de rotas. Uma conexão entre frontend e experiência em logística." accent="#ffb294"><div className="grid"><Stat label="Paradas" value={stops.length}/><Stat label="Distância geográfica (ida e volta)" value={km.toFixed(1) + ' km'}/><Stat label="Custo ilustrativo" value={new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(km * cost)}/></div><section className="panel" style={{ marginTop: 24 }}><h2>Adicionar destino</h2><form className="form" onSubmit={add}><label>Nome<input name="name" required maxLength={60}/></label><label>Latitude<input type="number" step="any" name="lat" min="-90" max="90" required/></label><label>Longitude<input type="number" step="any" name="lng" min="-180" max="180" required/></label><button className="primary">Adicionar</button></form></section><section className="panel"><div className="row spread"><h2>Sequência de entregas</h2><button className="primary" onClick={() => setOptimized(!optimized)}>{optimized ? 'Usar ordem original' : 'Usar vizinho mais próximo'}</button></div><p>Base: Guarulhos. Distâncias em linha geográfica pelo modelo de Haversine. A heurística não garante a melhor rota e não considera vias, trânsito ou pedágios.</p><label>Custo simulado por km (R$)<input type="number" min="0" step="0.1" value={cost} onChange={e => setCost(Math.max(0, Number(e.target.value)))}/></label><ol>{ordered.map((s, i) => <li key={s.id} className="card" style={{ marginTop: 16 }}><div className="row spread"><div><h3>{s.name}</h3><small>{s.lat.toFixed(4)}, {s.lng.toFixed(4)} • {distance(i ? ordered[i - 1] : depot, s).toFixed(1)} km desde a parada anterior</small></div><button aria-label={'Remover ' + s.name} onClick={() => setStops(stops.filter(x => x.id !== s.id))}>Remover</button></div></li>)}</ol>{!stops.length && <p className="empty">Adicione um destino para simular uma rota.</p>}{error && <p role="alert">As paradas não puderam ser salvas.</p>}<p>Retorno à base incluído: {ordered.length ? distance(ordered[ordered.length - 1], depot).toFixed(1) : '0'} km.</p></section></Shell>; }
